steps:
  - label: "Example Test"
    command: echo "Hello!"
  - label: "build ecucalibrator"
    retry:
      automatic:
      - limit: 3
        exit_status: -1
      - limit: 3
        exit_status: 137
      - limit: 3
        exit_status: 143
    agents:
      queue: "default"
    command:
    - "curl -sS https://raw.githubusercontent.com/bazelbuild/continuous-integration/master/buildkite/bazelci.py?1586563313 -o bazelci.py"
    - "python3.6 bazelci.py runner --task=ecucalibrator-build-linux --file_config=.bazelci/presubmit.yml"
    plugins:
      docker#v3.5.0:
        image: "gcr.io/bazel-public/ubuntu1804-java11"
        network: "host"
        volumes:
        - "/etc/group:/etc/group:ro"
        - "/etc/passwd:/etc/passwd:ro"
        - "/opt:/opt:ro"
        - "/var/lib/buildkite-agent:/var/lib/buildkite-agent"
        - "/var/lib/gitmirrors:/var/lib/gitmirrors:ro"
        - "/var/run/docker.sock:/var/run/docker.sock"
        privileged: true
        always-pull: true
        environment:
        - "ANDROID_HOME"
        - "ANDROID_NDK_HOME"
        - "BUILDKITE_ARTIFACT_UPLOAD_DESTINATION"
        propagate-uid-gid: true
        propagate-environment: true
    timeout_in_minutes: 480
  - label: "test ecucalibrator"
    retry:
      automatic:
      - limit: 3
        exit_status: -1
      - limit: 3
        exit_status: 137
      - limit: 3
        exit_status: 143
    agents:
      queue: "default"
    command:
    - "curl -sS https://raw.githubusercontent.com/bazelbuild/continuous-integration/master/buildkite/bazelci.py?1586563313 -o bazelci.py"
    - "python3.6 bazelci.py runner --task=ecucalibrator-test-linux --file_config=.bazelci/presubmit.yml"
    plugins:
      docker#v3.5.0:
        image: "gcr.io/bazel-public/ubuntu1804-java11"
        network: "host"
        volumes:
        - "/etc/group:/etc/group:ro"
        - "/etc/passwd:/etc/passwd:ro"
        - "/opt:/opt:ro"
        - "/var/lib/buildkite-agent:/var/lib/buildkite-agent"
        - "/var/lib/gitmirrors:/var/lib/gitmirrors:ro"
        - "/var/run/docker.sock:/var/run/docker.sock"
        privileged: true
        always-pull: true
        environment:
        - "ANDROID_HOME"
        - "ANDROID_NDK_HOME"
        - "BUILDKITE_ARTIFACT_UPLOAD_DESTINATION"
        propagate-uid-gid: true
        propagate-environment: true
    timeout_in_minutes: 480