steps:
  - label: "Example Test"
    command: echo "Hello!"
  - label: "build"
    command: bazel build --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 ...
  - label: "test"
    command: bazel test ...