steps:
  - label: "Example Test"
    command: echo "Hello!"
  - label: "login to GCR"
    command: "cat /root/gcr/config.json | docker login -u _json_key --password-stdin https://gcr.io"
  - label: "build"
    command: bazel build --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 ...
  - label: "test"
    command: bazel test ...