apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkite
spec:
  selector:
    matchLabels:
      app: buildkite
  replicas: 1
  template:
    metadata:
      labels:
        app: buildkite
    spec:
      containers:
        - name: buildkite
          image: buildkite/agent:3
          env:
            - name: BUILDKITE_AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: buildkite-agent-token
                  key: BUILDKITE_AGENT_TOKEN
