apiVersion: v1
kind: Pod
metadata:
  name: buildkite
  labels:
    name: buildkite
spec:
  volumes:
  - name: buildkite-github-ssh-volume
    secret:
      secretName: buildkite-github-ssh
      defaultMode: 0600
  - name: environment-hooks-volume
    configMap:
      name: add-env-key-hook
      items:
        - key: ADD_ENV_KEY_HOOK
          path: environment
  containers:
    - name: buildkite
      image: buildkite/agent:3
      env:
        - name: BUILDKITE_AGENT_TOKEN
          valueFrom:
            secretKeyRef:
              name: buildkite-agent-token
              key: BUILDKITE_AGENT_TOKEN
      volumeMounts:
      - name: buildkite-github-ssh-volume
        readOnly: true
        mountPath: "/buildkite-secrets"
      - name: environment-hooks-volume
        mountPath: "/buildkite/hooks"
