FROM buildkite/agent:3-ubuntu
RUN apt-get update 
# Install bazel (https://docs.bazel.build/versions/master/install-ubuntu.html)
RUN apt-get -y install openjdk-8-jdk
RUN echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list
RUN apt-get -y install gnupg
RUN curl https://bazel.build/bazel-release.pub.gpg | apt-key add -
RUN apt-get update

RUN apt-get -y install bazel
RUN apt-get -y upgrade bazel

RUN apt-get -y install python
RUN apt-get -y install python3

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash
RUN apt-get -y install nodejs
