kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  namespace: dev
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: frontend
          image: gcr.io/ecucalibrator/frontend:fd273f4fe16333fc60ab13b18d82367eca9579fe
