#!/bin/bash

GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
GIT_SHA=$(git rev-parse HEAD)
echo GIT_SHA $GIT_SHA

CONTAINER_REGISTRY=gcr.io/ecucalibrator/bazel-buildkite
echo CONTAINER_REGISTRY $CONTAINER_REGISTRY
